### ISSUE TITLE
Problem when cloning the TimeEval repo

### ISSUE THREAD

**Issue by SpaceCyberCoffee** [kplabs-pl/ESA-ADB#1]
Hi,
I am trying to install from source, but when I am trying to clone TimeEval:

`git clone git@gitlab.hpi.de:akita/bp2020fn1/timeeval.git`

I get the following error:

```
Cloning into 'timeeval'...
ssh: connect to host gitlab.hpi.de port 22: Network is unreachable
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is it possible to host it on GitHub or on a public GitLab repo?

Thanks in advance!

**Comment by Kotrix** [comment]
Hi, you do not need to clone the original TimeEval repository. All you need is already in the "timeeval" folder in our repository. I've removed the TimeEval installation instruction from the README to avoid confusion.
